name: @name@
version: @version@
main: @package@.@name@
api-version: '1.21'
load: STARTUP
authors: [TropicalShadow]
description: Templatable plugin for quicker development
website: https://me.tesseract.club
